// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAisv1aMOrJEOjMhG6rTkPYX-V4_qmOmnI',
    appId: '1:17136520807:web:f45f892647efdb77c98ec2',
    messagingSenderId: '17136520807',
    projectId: 'kwik-mart-store',
    authDomain: 'kwik-mart-store.firebaseapp.com',
    storageBucket: 'kwik-mart-store.appspot.com',
    measurementId: 'G-7ST4BSK6NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU80orlUXDX-fB8JjicHPiPGjua3As-IQ',
    appId: '1:17136520807:android:069e93d15f1dcc5dc98ec2',
    messagingSenderId: '17136520807',
    projectId: 'kwik-mart-store',
    storageBucket: 'kwik-mart-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzOnZGHvHA0rTe0E6VlL11wHr7kkufLKY',
    appId: '1:17136520807:ios:996b261f45b2d479c98ec2',
    messagingSenderId: '17136520807',
    projectId: 'kwik-mart-store',
    storageBucket: 'kwik-mart-store.appspot.com',
    iosClientId: '17136520807-ed9702d4vud5gpllhttuo6f72rugug5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.kwikMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzOnZGHvHA0rTe0E6VlL11wHr7kkufLKY',
    appId: '1:17136520807:ios:6236f30eeb83a67bc98ec2',
    messagingSenderId: '17136520807',
    projectId: 'kwik-mart-store',
    storageBucket: 'kwik-mart-store.appspot.com',
    iosClientId: '17136520807-b752featfjsphu8povo24gcdokddc6eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.kwikMart.RunnerTests',
  );
}
